sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "8"
script:
  - npm test
after_success:
  - npx codecov
branches:
  only:
    - master
